openapi: 3.0.1
info:
  title: Vexl Converter API
  description: "API for converting data between various formats (hex, base64, binary,\
    \ decimal, ascii)"
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Local Development Server
tags:
- name: Conversion
  description: Data format conversion operations
paths:
  /api/convert:
    post:
      tags:
      - Conversion
      summary: Convert data between formats
      description: "Converts input data from one format to another. Supported formats:\
        \ hex, base64, binary, decimal, ascii"
      operationId: convert
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConversionRequest"
        required: true
      responses:
        "200":
          description: Conversion successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConversionResponse"
        "400":
          description: Invalid input or unsupported format
  /api/formats:
    get:
      tags:
      - Conversion
      summary: Get supported formats
      description: Returns a list of all supported conversion formats
      operationId: getSupportedFormats
      responses:
        "200":
          description: List of supported formats
          content:
            application/json:
              schema:
                type: string
  /api/health:
    get:
      tags:
      - Conversion
      summary: Health check
      description: Returns the health status of the API
      operationId: health
      responses:
        "200":
          description: API is healthy
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    ConversionRequest:
      required:
      - fromFormat
      - input
      - toFormat
      type: object
      properties:
        input:
          minLength: 1
          type: string
          description: Input data to be converted
          example: 48656c6c6f
        fromFormat:
          minLength: 1
          type: string
          description: Source format of the input data
          example: hex
          enum:
          - hex
          - base64
          - binary
          - decimal
          - ascii
        toFormat:
          minLength: 1
          type: string
          description: Target format for conversion
          example: base64
          enum:
          - hex
          - base64
          - binary
          - decimal
          - ascii
      description: Request object for data format conversion
    ConversionResponse:
      type: object
      properties:
        output:
          type: string
          description: Converted output data
          nullable: true
          example: SGVsbG8=
        success:
          type: boolean
          description: Indicates if conversion was successful
          example: true
        error:
          type: string
          description: Error message if conversion failed
          nullable: true
      description: Response object containing conversion result
